name: cpu-testrun

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches: [master]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  train-and-cross-check:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Checkout Compatible Stockfish Repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          repository: TonyCongqianWang/Stockfish
          path: Stockfish
          ref: 37c8612cabc334fc8af6dc6a603a3db7a77c2fa9
          persist-credentials: false

      - name: Compile Compatible Stockfish
        run: |
          cd Stockfish/src
          make -j build

      - name: Perform Test Run of entire Training Pipeline on CPU
        run: |
          ./run_docker.sh CPU ${{ github.workspace }} --non-interactive --exec \
            python -u tests/test_training_pipeline_run.py -y --device cpu --test-dir /data/logs/training/runs/unittests_train_pipeline_cpu

      - name: Perform Cross-Check Evaluation (.nnue)
        run: |
          ./run_docker.sh CPU ${{ github.workspace }} --skip-setup --non-interactive --exec \
            python -u cross_check_eval.py --net /data/logs/training/runs/unittests_train_pipeline_cpu/lightning_logs/version_2/checkpoints/last.nnue --data .pgo/small.binpack --engine ./Stockfish/src/stockfish --device='cpu'

      - name: Perform Cross-Check Evaluation (.ckpt)
        run: |
          ./run_docker.sh CPU ${{ github.workspace }} --skip-setup --non-interactive --exec \
            python -u cross_check_eval.py --net /data/logs/training/runs/unittests_train_pipeline_cpu/lightning_logs/version_2/checkpoints/last.nnue --data .pgo/small.binpack --engine ./Stockfish/src/stockfish --device='cpu' \
            --checkpoint /data/logs/training/runs/unittests_train_pipeline_cpu/lightning_logs/version_2/checkpoints/last.ckpt
