name: training-data-loader

on: [workflow_call]

jobs:
  build-and-bench:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Compile using cmake
        run: ./compile_data_loader.sh

      - name: Run cmake compiled benchmark (100 iterations)
        run: ./build/training_data_loader_bench -i 100 ./.pgo/small.binpack

      - name: Run cmake compiled report (50 iterations)
        run: ./build/training_data_loader_report -i 50 ./.pgo/small.binpack

